# Generated by Django 4.0.1 on 2023-11-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
